<!DOCTYPE html>
<html>
<head>
    <title>Usage Report - {{ $report->month_year }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .report-title { font-size: 20px; font-weight: bold; text-transform: uppercase; }
        .stats-container { width: 100%; margin-bottom: 30px; }
        /* Adjusted to 4 boxes to fit the new category */
        .stat-box { width: 22%; float: left; padding: 10px; border: 1px solid #ddd; text-align: center; margin-right: 1%; font-size: 11px; }
        .clear { clear: both; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f2f2f2; padding: 8px; border: 1px solid #ddd; text-align: left; }
        td { padding: 8px; border: 1px solid #ddd; }
        .text-right { text-align: right; }
        .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #777; }
        .highlight { color: #4f46e5; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <div class="report-title">Monthly Usage Report</div>
        <div>Gedung Braga 8 - Management System</div>
        <div>Periode: {{ \Carbon\Carbon::parse($report->month_year)->format('F Y') }}</div>
    </div>

    <div class="stats-container">
        <div class="stat-box">
            <strong>Electric Revenue</strong><br>
            Rp {{ number_format($report->total_electric_usage) }}
        </div>
        <div class="stat-box">
            <strong>Water Revenue</strong><br>
            Rp {{ number_format($report->total_water_usage) }}
        </div>
        <div class="stat-box">
            <strong>Service/Other Fees</strong><br>
            @php 
                $others = $report->total_revenue_expected - ($report->total_electric_usage + $report->total_water_usage);
            @endphp
            Rp {{ number_format($others) }}
        </div>
        <div class="stat-box" style="background: #f9fafb; border: 2px solid #333;">
            <strong class="highlight">TOTAL REVENUE</strong><br>
            <strong>Rp {{ number_format($report->total_revenue_expected) }}</strong>
        </div>
        <div class="clear"></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Unit</th>
                <th>Tenant</th>
                <th>Invoice No</th>
                <th class="text-right">Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoices as $inv)
            <tr>
                <td>{{ $inv->unit->unit_number }}</td>
                <td>{{ $inv->tenant->tenant_name }}</td>
                <td>{{ $inv->invoice_number }}</td>
                <td class="text-right">Rp {{ number_format($inv->total_amount) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Braga 8 System on {{ now()->format('d/m/Y H:i') }}
    </div>

</body>
</html>